### ISSUE TITLE
Implementation of GRCh38 

### ISSUE THREAD

**Issue by IanCodes** [Pitithat-pu/cfdnakit#11]
What would be required to use the GCRh38 (hg38) human reference sequence?  Is it something that I could do myself?
Thank you.

**Comment by Pitithat-pu** [comment]
@IanCodes Sorry for late reply, you can simply change "genome" argument to hg38 when you read bamfile with read_bamfile
`read_bamfile(bamfile,binsize = 1000,
                    genome = "hg38")`
